baseURL = "https://ovh.github.io/cds"
title = "CDS - Continuous Delivery Service"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
contentDir = "content"

disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyurls = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
